### ISSUE TITLE
About SE layer in Fused-MBConv

### ISSUE THREAD

**Issue by Noir97** [d-li14/efficientnetv2.pytorch#5]
<img width="327" alt="截屏2021-04-21 下午3 32 37" src="https://user-images.githubusercontent.com/37800725/115514568-cfdc4900-a2b6-11eb-8adc-de6dc1f2c993.png">
I understand that the SE layer might get removed in the original fusion attempt: https://ai.googleblog.com/2019/08/efficientnet-edgetpu-creating.html

But according to Fig2 in the paper, it seems like the SE layer is preserved in the Fused MBConv. So I am quite confused when I  found the SE layer lacking in your implementation. Have you ever tried the implementation with SE layer, or am I missing something in the paper?

**Comment by Noir97** [comment]
OK...I guess the missing SE parameter in the architecture table implies that. Nevermind.

**Comment by xiaoerlaigeid** [comment]
> OK...I guess the missing SE parameter in the architecture table implies that. Nevermind.

I also notice this implementation lack of SE layer in Fused MBConv. Could further explain about this ?

**Comment by Noir97** [comment]
> > OK...I guess the missing SE parameter in the architecture table implies that. Nevermind.
> 
> I also notice this implementation lack of SE layer in Fused MBConv. Could further explain about this ?

<img width="779" alt="截屏2021-05-14 下午12 44 19" src="https://user-images.githubusercontent.com/37800725/118222373-1d149a80-b4b2-11eb-9763-fa876349699b.png">

In the architecture table, "SE" shows up but only with normal MBConv, I guess that means it is not used with Fused MBConv

**Comment by xiaoerlaigeid** [comment]
Oh thanks！
