### ISSUE TITLE
Syncing with the implementation of official repo

### ISSUE THREAD

**Issue by seermer** [d-li14/efficientnetv2.pytorch#9]
The official repo made some changes that are different from the paper.
For example, the paper claims that v2-s uses 272 channels in the last stage, but they changed to 256 in their code, and the author claimed that the code will be the source of truth. Is this repo planning on syncing with the official code?
Thanks

**Comment by launchauto** [comment]
Yes, it is 256

https://github.com/d-li14/efficientnetv2.pytorch/blob/775326e6c16bfc863e9b8400eca7d723dbfeb06e/effnetv2.py#L179
the c column indicates the output of efficientnetv2-s backbone (before the last layer conv-avgpool-linear) is 256.
Or you can put the code in your program and see the output tensor size.
